<?php

declare(strict_types=1);

namespace LauLamanApps\IzettleApi\API\Finance\Enum;

use Werkspot\Enum\AbstractEnum;

final class TransactionType extends AbstractEnum
{
    const CARD_PAYMENT ='CARD_PAYMENT';
    const CARD_REFUND ='CARD_REFUND';
    const BANK_ACCOUNT_VERIFICATION ='BANK_ACCOUNT_VERIFICATION';
    const PAYOUT ='PAYOUT';
    const FAILED_PAYOUT ='FAILED_PAYOUT';
    const CASH_BACK ='CASHBACK';
    const CASH_BACK_PAYOUT ='CASHBACK_PAYOUT';
    const VOUCHER_ACTIVATION ='VOUCHER_ACTIVATION';
    const E_MONEY_TRANSFER ='EMONEY_TRANSFER';
    const TELL_FRIEND ='TELL_FRIEND';
    const FROZEN_FUNDS ='FROZEN_FUNDS';
    const FEE_DISCOUNT_REVOCATION ='FEE_DISCOUNT_REVOCATION';
    const CARD_PAYMENT_FEE ='CARD_PAYMENT_FEE';
    const CARD_PAYMENT_FEE_REFUND ='CARD_PAYMENT_FEE_REFUND';
    const ADVANCE ='ADVANCE';
    const ADVANCE_FEE ='ADVANCE_FEE';
    const ADVANCE_DOWN_PAYMENT ='ADVANCE_DOWNPAYMENT';
    const ADVANCE_FEE_DOWN_PAYMENT ='ADVANCE_FEE_DOWNPAYMENT';
    const SUBSCRIPTION_CHARGE ='SUBSCRIPTION_CHARGE';
    const INVOICE_PAYMENT ='INVOICE_PAYMENT';
    const INVOICE_PAYMENT_FEE ='INVOICE_PAYMENT_FEE';
    const ADJUSTMENT ='ADJUSTMENT';
}
