<?php

declare(strict_types=1);

namespace LauLamanApps\IzettleApi\API\Finance\Enum;

enum TransactionType: string
{
    case CARD_PAYMENT = 'CARD_PAYMENT';
    case CARD_REFUND = 'CARD_REFUND';
    case BANK_ACCOUNT_VERIFICATION = 'BANK_ACCOUNT_VERIFICATION';
    case PAYOUT = 'PAYOUT';
    case FAILED_PAYOUT = 'FAILED_PAYOUT';
    case CASH_BACK = 'CASHBACK';
    case CASH_BACK_PAYOUT = 'CASHBACK_PAYOUT';
    case VOUCHER_ACTIVATION = 'VOUCHER_ACTIVATION';
    case EMONEY_TRANSFER = 'EMONEY_TRANSFER';
    case TELL_FRIEND = 'TELL_FRIEND';
    case FROZEN_FUNDS = 'FROZEN_FUNDS';
    case FEE_DISCOUNT_REVOCATION = 'FEE_DISCOUNT_REVOCATION';
    case CARD_PAYMENT_FEE = 'CARD_PAYMENT_FEE';
    case CARD_PAYMENT_FEE_REFUND = 'CARD_PAYMENT_FEE_REFUND';
    case ADVANCE = 'ADVANCE';
    case ADVANCE_FEE = 'ADVANCE_FEE';
    case ADVANCE_DOWN_PAYMENT = 'ADVANCE_DOWNPAYMENT';
    case ADVANCE_FEE_DOWN_PAYMENT = 'ADVANCE_FEE_DOWNPAYMENT';
    case SUBSCRIPTION_CHARGE = 'SUBSCRIPTION_CHARGE';
    case INVOICE_PAYMENT = 'INVOICE_PAYMENT';
    case INVOICE_PAYMENT_FEE = 'INVOICE_PAYMENT_FEE';
    case ADJUSTMENT = 'ADJUSTMENT';
}
