<?php

declare(strict_types=1);

namespace LauLamanApps\iZettleApi\Tests\Unit\Client\Purchase;

use LauLamanApps\iZettleApi\API\Image;
use LauLamanApps\iZettleApi\API\Purchase\Product;
use LauLamanApps\iZettleApi\Client\Purchase\ProductParser;
use Money\Currency;
use PHPUnit\Framework\TestCase;

/**
 * @small
 */
final class ProductParserTest extends TestCase
{
    /**
     * @test
     */
    public function parseArray()
    {
        $data = $this->getProductData();

        $products = ProductParser::parseArray($data, new Currency('EUR'));

        foreach ($products as $index => $product) {
            self::assertInstanceOf(Product::class, $product);
            self::assertSame($data[$index]['unitPrice'], (int) $product->getUnitPrice()->getAmount());
            self::assertSame($data[$index]['rowTaxableAmount'], (int) $product->getRowTaxableAmount()->getAmount());
            self::assertSame($data[$index]['vatPercentage'], $product->getVatPercentage());
            self::assertSame((int) $data[$index]['quantity'], $product->getQuantity());
            self::assertSame($data[$index]['autoGenerated'], $product->isAutoGenerated());
            self::assertSame($data[$index]['libraryProduct'], $product->isLibraryProduct());

            if (array_key_exists('productUuid', $data[$index])) {
                self::assertSame($data[$index]['productUuid'], (string)$product->getProductUuid());
            }
            if (array_key_exists('variantUuid', $data[$index])) {
                self::assertSame($data[$index]['variantUuid'], (string) $product->getVariantUuid());
            }
            if (array_key_exists('name', $data[$index])) {
                self::assertSame($data[$index]['name'], $product->getName());
            }
            if (array_key_exists('variantName', $data[$index])) {
                self::assertSame($data[$index]['variantName'], $product->getVariantName());
            }
            if (array_key_exists('imageLookupKey', $data[$index])) {
                self::assertInstanceOf(Image::class, $product->getImageLookupKey());
                self::assertSame($data[$index]['imageLookupKey'], $product->getImageLookupKey()->getFilename());
            }
        }
    }

    private function getProductData()
    {
        return [
            [
                "quantity" => "1",
                "vatPercentage" => 21.0,
                "unitPrice" => 100,
                "rowTaxableAmount" => 83,
                "autoGenerated" => false,
                "libraryProduct" => false,
            ],
            [
                "quantity" => "1",
                "productUuid" => "3b3565e0-2694-11e7-b983-c70f05a416cd",
                "variantUuid" => "56afb320-2694-11e7-b983-c70f05a416cd",
                "vatPercentage" => 0.0,
                "unitPrice" => 500,
                "rowTaxableAmount" => 500,
                "name" => "Munten",
                "variantName" => "10 munten",
                "imageLookupKey" => "Image.jpg",
                "autoGenerated" => false,
                "libraryProduct" => true
            ]
        ];
    }
}
