name: "Run unit tests"

on:
  pull_request:
  push:
    branches:
        - master

jobs:
  test:
    name: "Test on PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'

        include:
          - php: '8.1'
            main: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: xdebug
          tools: php-parallel-lint/php-parallel-lint

      - name: Lint PHP code
        run: parallel-lint .

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--ignore-platform-req=php"

      - name: Validate formatting
        run: composer run format -- --dry-run
        if: matrix.main

      - name: Run tests
        run: composer run test-coverage

      - name: Determine coverage
        uses: slavcodev/coverage-monitor-action@v1
        if: matrix.main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: coverage/clover.xml
          threshold_alert: 75
          threshold_warning: 95
